input_channel: 3
depth_multiple: 1.0
width_multiple: 1.0
backbone: [
    [1, Conv, [16, 3, 2, 1]], 
    [1, MaxPool, [3, 2, 1]],
    [1, GhostBottleneck, [3, 5.9, 64, 0, 2]], 
    [1, InvertedResidualv3, [3, 2.1, 80, 0, 0, 2]], 
    [3, InvertedResidualv2, [64, 1, 1]], 
    [1, MBConv, [1, 96, 1, 3, 0]], 
    [1, MaxPool, [3, 2, 1]], 
    [1, Conv, [1024, 1, 1]], 
    [1, GlobalAvgPool, []],
    [1, Flatten, []], 
    [1, Linear, [3]]]
input_size: [128, 128]
