input_channel: 3
depth_multiple: 1.0
width_multiple: 1.0
backbone: [[1, Conv, [24, 3, 2, null, 1, ReLU]], [1, MaxPool, [3, 2, 1]], [1, ECAInvertedResidualv2,
    [48, 3, 2]], [1, ECAInvertedResidualv3, [3, 4.6, 48, 1, 1, 2]], [2, ECABottleneck,
    [64]], [1, MaxPool, [3, 2, 1]], [1, ECABottleneck, [208]], [1, MBConv, [1, 240,
      1, 3]], [1, Conv, [512, 1, 1]], [1, GlobalAvgPool, []], [1, Flatten, []], [
    1, Linear, [9]]]
input_size: [32, 32]
