input_channel: 3
depth_multiple: 1.0
width_multiple: 1.0
backbone: [[1, Conv, [24, 3, 2, null, 1, ReLU]], [1, MaxPool, [3, 2, 1]], [2, GhostBottleneck,
    [3, 1.0, 64, 1, 1]], [1, MaxPool, [3, 2, 1]], [1, InvertedResidualv3, [3, 1.7,
      64, 0, 1, 2]], [4, GhostBottleneck, [3, 1.0, 64, 1, 1]], [1, MaxPool, [3, 2,
      1]], [2, ECAInvertedResidualv2, [144, 2, 1]], [1, ECAInvertedResidualv2, [144,
      1, 1]], [1, Conv, [768, 1, 1]], [1, GlobalAvgPool, []], [1, Flatten, []], [
    1, Linear, [9]]]
input_size: [32, 32]
